### ISSUE TITLE
Border is not been taken into account when calculating component height

### ISSUE THREAD

**Issue by natete** [shevaroller/angular-autosize#2]
Border is not been taken into account when calculating the textarea height, this can lead to some bad behavior depending on the styles, a big padding can provoke a scroll to appear even on init.

Find [here](https://stackblitz.com/edit/angular-vqrg6e) an example:

**Comment by alexshevch** [comment]
Hi, thank you for following up the issue with a PR, I am going to test the changes and merge them in shortly.
